### ISSUE TITLE
Couldn't build OpenMVG on Mac

### ISSUE THREAD

**Issue by cmdavies** [openMVG/openMVG#1296]
Hello all,

I am trying to build OpenMVG after following the build instruction for Mac OS. However it failed with the following compilation messages. It seems that OpenMp is not found. However, I have downloaded both gcc and llvm and changed the environment variables to point to the correct lib and include directories. I have tried to compile (with both clang and gcc compilers) using some simplest code with OpenMp lines and it compiles and works file. However if I build OpenMVG using:

```
cmake -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON -fopenmp . ../openMVG/src/
```

it fails and the compilation messages are as follows. Any ideas for why it isn't working? I have been stuck for a little while... Thanks a lot for your help!
```
-- Checking for C++11 compiler
-- Checking for C++11 compiler - available
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS) 
-- Eigen 3.3.4 found (include: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/eigen)
-- Flann 1.8.4 found (include: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/flann/src/cpp/flann)
-- CoinUtils 2.10.13 found (include: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/dependencies/osi_clp/CoinUtils/src)
-- Clp 1.16.10 found (include: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/dependencies/osi_clp/Clp/src)
-- Osi 0.107.8 found (include: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/dependencies/osi_clp/Osi/src/Osi)
-- Lemon 1.3 found (include: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/lemon/lemon)
-- Could NOT find Wget (missing:  WGET_EXECUTABLE) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Could NOT find Ghostscript (missing:  GHOSTSCRIPT_EXECUTABLE) 
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")
-- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR) 
-- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY COIN_OSI_CLP_LIBRARY) 
-- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR) 

   ===============================================================
   Ceres-solver configuration.
   ===============================================================
-- Detected Ceres version: 1.13.0 from /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/ceres-solver/include/ceres/version.h
-- Eigen 3.3.4 found (include: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/eigen)
-- Found Eigen version 3.3.4: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- A library with BLAS API found.
-- Found LAPACK library: /System/Library/Frameworks/Accelerate.framework;/System/Library/Frameworks/Accelerate.framework
-- Found BLAS library: /System/Library/Frameworks/Accelerate.framework
-- Building without SuiteSparse.
-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.
-- Google Flags disabled; no tests or tools will be built!
-- Compiling minimal glog substitute into Ceres.
-- Using minimal glog substitute (include): internal/ceres/miniglog
-- Building without OpenMP (disabling multithreading).
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - found
-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
-- Found unordered_map/set in std namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
-- Enabling CERES_NO_SUITESPARSE in Ceres config.h
-- Enabling CERES_NO_THREADS in Ceres config.h
-- Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
-- Do not build any example.
   ===============================================================
   Ceres-solver configuration end.
   ===============================================================
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS) 
CMake Warning at third_party/flann/CMakeLists.txt:75 (message):
  OpenMP NOT found


CMake Warning at third_party/eigen/CMakeLists.txt:67 (message):
  EIGEN_INCLUDE_INSTALL_DIR is deprecated.  Use INCLUDE_INSTALL_DIR instead.


-- 
-- Configured Eigen 3.3.4
-- 
CMake Warning at openMVG_Samples/describe_and_match_GUI/CMakeLists.txt:4 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at software/VO/AlternativeVO/CMakeLists.txt:6 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at software/CMakeLists.txt:14 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


** Qt5 not found, GUI modules will not be build
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
Sphinx need to be installed to generate the sphinx documentation
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation


** OpenMVG version: 1.3.0
** Build Shared libs: OFF
** Build OpenMVG tests: ON
** Build OpenMVG softwares: ON
** Build OpenMVG documentation: ON
** Build OpenMVG samples applications: ON
** Build OpenMVG openGL examples: OFF
** Enable code coverage generation: OFF
** Enable OpenMP parallelization: ON
** Build OpenCV+OpenMVG samples programs: OFF
** Use OpenCV SIFT features: OFF


-- CEREAL: (internal)
-- EIGEN: 3.3.4 (internal)
-- CERES: 1.13.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF:  (internal)
-- LIBPNG:  (internal)
-- LIBJPEG (internal)
-- CLP: 1.16.10 (internal)
-- COINUTILS: 2.10.13 (internal)
-- OSI: 0.107.8 (internal)
-- LEMON: 1.3 (internal)


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/chendavies/Documents/LatchAid/LatchAid/openMVG
```

**Comment by cmdavies** [comment]
Hello Pierre,

Thanks a lot for your reply and help! Here are my questions:

*1) I don't see any message of "QT is not detected and so QT examples will
not be built" from the below message though?*

clang detected: using std::unordered_map for Hash_Map

-- Checking for C++11 compiler

-- Checking for C++11 compiler - available

-- Try OpenMP C flag = [ ]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-fopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-fopenmp=libomp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [/openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-Qopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-xopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [+Oopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-qsmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-mp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [ ]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-fopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-fopenmp=libomp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [/openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-Qopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-xopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [+Oopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-qsmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-mp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS)

-- Eigen 3.3.4 found (include: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/third_party/eigen)

-- Flann 1.8.4 found (include: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/third_party/flann/src/cpp/flann)

-- CoinUtils 2.10.13 found (include: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/dependencies/osi_clp/CoinUtils/src)

-- Clp 1.16.10 found (include: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/dependencies/osi_clp/Clp/src)

-- Osi 0.107.8 found (include: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/dependencies/osi_clp/Osi/src/Osi)

-- Lemon 1.3 found (include: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/third_party/lemon/lemon)

-- Could NOT find Wget (missing:  WGET_EXECUTABLE)

-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)

-- Could NOT find Ghostscript (missing:  GHOSTSCRIPT_EXECUTABLE)

-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR
GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")

-- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY
ILOG_CPLEX_INCLUDE_DIR)

-- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY
COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY
COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY
COIN_OSI_CLP_LIBRARY)

-- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)


   ===============================================================

   Ceres-solver configuration.

   ===============================================================

-- Detected Ceres version: 1.13.0 from /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/third_party/ceres-solver/include/ceres/version.h

-- Eigen 3.3.4 found (include: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/third_party/eigen)

-- Found Eigen version 3.3.4: /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/third_party/eigen


   ===============================================================

   Disabling the use of Eigen as a sparse linear algebra library.

   This does not affect the covariance estimation algorithm

   which can still use the EIGEN_SPARSE_QR algorithm.

   ===============================================================


-- A library with BLAS API found.

-- Found LAPACK library: /Applications/Xcode.app/Conten
ts/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.13.sdk/System/Library/Frameworks/Accelerate.framewo
rk;/Applications/Xcode.app/Contents/Developer/Platforms/
MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/
Library/Frameworks/Accelerate.framework

-- Found BLAS library: /Applications/Xcode.app/Conten
ts/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.13.sdk/System/Library/Frameworks/Accelerate.framework

-- Building without SuiteSparse.

-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.

-- Google Flags disabled; no tests or tools will be built!

-- Compiling minimal glog substitute into Ceres.

-- Using minimal glog substitute (include): internal/ceres/miniglog

-- Building without OpenMP (disabling multithreading).

-- Looking for C++ include unordered_map

-- Looking for C++ include unordered_map - not found

-- Looking for C++ include tr1/unordered_map

-- Looking for C++ include tr1/unordered_map - not found

-- Unable to find <unordered_map> or <tr1/unordered_map>.

-- Replacing unordered_map/set with map/set (warning: slower!), try
enabling CXX11 option if you expect C++11 to be available.

-- Looking for C++ include memory

-- Looking for C++ include memory - not found

-- Looking for C++ include tr1/memory

-- Looking for C++ include tr1/memory - not found

CMake Error at third_party/ceres-solver/CMakeLists.txt:454 (message):

  Unable to find shared_ptr, try enabling CXX11 option if you expect C++11
to

  be available.


*2) And I did: *

*cd ../openMVG *

*make -i (to get over some build errors of SIFT etc)*


*most of things build ok, but I get the errors as follows:*


[ 89%] Building C object nonFree/sift/CMakeFiles/vlsift
.dir/vl/imopv_sse2.c.o

In file included from /Users/chendavies/Documents/La
tchAid/LatchAid/openMVG/src/nonFree/sift/vl/imopv_sse2.c:22:

In file included from /usr/local/Cellar/gcc/7.3.0_1/
lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/emmintrin.h:31:

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:52:1:
*
*error: *

*      conflicting types for '_mm_prefetch'*

_mm_prefetch (const void *__P, enum _mm_hint __I)

*^*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:52:1:
note: *

      '_mm_prefetch' is a builtin with type 'void (const char *, int)'

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:52:1:
*
*error: *

*      definition of builtin function '_mm_prefetch'*

_mm_prefetch (const void *__P, enum _mm_hint __I)

*^*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:54:3:
*
*error: *

*      argument to '__builtin_prefetch' must be a constant integer*

  __builtin_prefetch (__P, (__I & 0x4) >> 2, __I & 0x3);

*  ^                        ~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:130:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_addss ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:136:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_subss ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:142:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:148:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_divss ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:242:10:
*
*error: *

*      returning 'int' from a function with incompatible result type
'__m128'*

*      (vector of 4 'float' values)*

  return __builtin_ia32_andps (__A, __B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:248:10:
*
*error: *

*      returning 'int' from a function with incompatible result type
'__m128'*

*      (vector of 4 'float' values)*

  return __builtin_ia32_andnps (__A, __B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:254:10:
*
*error: *

*      returning 'int' from a function with incompatible result type
'__m128'*

*      (vector of 4 'float' values)*

  return __builtin_ia32_orps (__A, __B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:260:10:
*
*error: *

*      returning 'int' from a function with incompatible result type
'__m128'*

*      (vector of 4 'float' values)*

  return __builtin_ia32_xorps (__A, __B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:288:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_movss ((__v4sf) __A,

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:298:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_movss ((__v4sf) __A,

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:326:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_movss ((__v4sf) __A,

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:336:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_movss ((__v4sf) __A,

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:380:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_cmpgtps ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:386:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_cmpgeps ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:410:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_cmpngtps ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*/usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin17.3.0/7.3.0/include/xmmintrin.h:416:10:
*
*error: *

*      invalid conversion between vector type '__m128' (vector of 4 'float'
values) and integer type*

*      'int' of different size*

  return (__m128) __builtin_ia32_cmpngeps ((__v4sf)__A, (__v4sf)__B);

*         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

*fatal error: *too many errors emitted, stopping now [-ferror-limit=]

20 errors generated.


[ 91%] Building CXX object software/SfM/CMakeFiles/openMV
G_main_openMVG2openMVS.dir/main_openMVG2openMVS.cpp.o

In file included from
*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/main_openMVG2openMVS.cpp:18:0*
:

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/cmdLine/cmdLine.h:163:43:*
 *warning: *dynamic exception specifications are deprecated in C++11 [
*-Wdeprecated*]

     void process(int& argc, char* argv[]) *throw*(std::string) {

                                           *^~~~~*

In file included from
*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/main_openMVG2openMVS.cpp:16:0*
:

/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:
In instantiation of '*bool MVS::ARCHIVE::Save(MVS::ARCHIVE::ArchiveSave&,
const _Tp&) [with _Tp = long unsigned int]*':

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:255:14:*
required from here

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:121:24:*
 *error: *request for member '*serialize*' in '*(long unsigned int&)(& obj)*',
which is of non-class type '*long unsigned int*'

  *const_cast<_Tp&>(obj).serialize*(a, a.version);

  *~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~*

/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:
In instantiation of '*bool MVS::ARCHIVE::Load(MVS::ARCHIVE::ArchiveLoad&,
_Tp&) [with _Tp = long unsigned int]*':

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:263:14:*
required from here

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:126:6:*
 *error: *request for member '*serialize*' in '*obj*', which is of
non-class type '*long unsigned int*'

  *obj.serialize*(a, a.version);

  *~~~~^~~~~~~~~*

[ 91%] *Linking CXX executable
../../Darwin-x86_64-RELEASE/openMVG_main_openMVG2openMVS*

*g++-7:* *error: *CMakeFiles/openMVG_main_openMVG2openMVS.
dir/main_openMVG2openMVS.cpp.o: No such file or directory



*3) And in the same directory as 2), when I then did make install, I get
the following error:*


CMake Error at software/SfM/cmake_install.cmake:51 (file):

  file INSTALL cannot find

  "/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/
Darwin-x86_64-RELEASE/openMVG_main_ComputeFeatures".

Call Stack (most recent call first):


Thanks a lot for your help!


Best Regards,


Chen

**Comment by igorti** [comment]
Try setting compiler flags like below for OpenMP to find it:

```
export CC=/usr/local/bin/gcc-7
export CXX=/usr/local/bin/c++-7
export CPP=/usr/local/bin/cpp-7
export LD=/usr/local/bin/gcc-7
export CPPFLAGS='-I/usr/local/include/'
export LDFLAGS='-L/usr/local/lib/'
```

Also, if you install dependencies with Homebrew they'll be build with builtin compiler and won't work when you build OpenMVG. I found easiest way around is to comment out lines of code in CMakeList file that tries find dependencies, so that OpenMVG builds all dependencies internally with gcc.

**Comment by cmdavies** [comment]
Hello Igor,

Thanks a lot for your information. I have the following three questions:

1) I have changed my .profile file to update the environment variables as
you suggested and used the following instead:

export CC=/usr/local/bin/gcc-7
export CXX=/usr/local/bin/c++-7
export CPP=/usr/local/bin/cpp-7
export LD=/usr/local/bin/gcc-7
export CPPFLAGS='-I/usr/local/include/c++/7.3.0'
export LDFLAGS='-L/usr/local/lib/'

But when I use make, I still get the following errors. It seems that
OpenMp is still not detected. And I'm not sure why I get "Looking for
C++ include unordered_map - not found" while they are available at
/usr/local/include/c++/7.3.0?

clang detected: using std::unordered_map for Hash_Map

-- Checking for C++11 compiler

-- Checking for C++11 compiler - available

-- Try OpenMP C flag = [ ]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-fopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-fopenmp=libomp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [/openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-Qopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-xopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [+Oopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-qsmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP C flag = [-mp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [ ]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-fopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-fopenmp=libomp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [/openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-Qopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-openmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-xopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [+Oopenmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-qsmp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Try OpenMP CXX flag = [-mp]

-- Performing Test OpenMP_FLAG_DETECTED

-- Performing Test OpenMP_FLAG_DETECTED - Failed

-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS)

-- Eigen 3.3.4 found (include:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/eigen)

-- Flann 1.8.4 found (include:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/flann/src/cpp/flann)

-- CoinUtils 2.10.13 found (include:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/dependencies/osi_clp/CoinUtils/src)

-- Clp 1.16.10 found (include:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/dependencies/osi_clp/Clp/src)

-- Osi 0.107.8 found (include:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/dependencies/osi_clp/Osi/src/Osi)

-- Lemon 1.3 found (include:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/lemon/lemon)

-- Could NOT find Wget (missing:  WGET_EXECUTABLE)

-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)

-- Could NOT find Ghostscript (missing:  GHOSTSCRIPT_EXECUTABLE)

-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR
GLPK_PROPER_VERSION_FOUND) (Required is at least version "4.33")

-- Could NOT find ILOG (missing:  ILOG_CPLEX_LIBRARY ILOG_CPLEX_INCLUDE_DIR)

-- Could NOT find COIN (missing:  COIN_INCLUDE_DIR COIN_CBC_LIBRARY
COIN_CBC_SOLVER_LIBRARY COIN_CGL_LIBRARY COIN_CLP_LIBRARY
COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY COIN_OSI_CBC_LIBRARY
COIN_OSI_CLP_LIBRARY)

-- Could NOT find SOPLEX (missing:  SOPLEX_LIBRARY SOPLEX_INCLUDE_DIR)


   ===============================================================

   Ceres-solver configuration.

   ===============================================================

-- Detected Ceres version: 1.13.0 from
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/ceres-solver/include/ceres/version.h

-- Eigen 3.3.4 found (include:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/eigen)

-- Found Eigen version 3.3.4:
/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/eigen


   ===============================================================

   Disabling the use of Eigen as a sparse linear algebra library.

   This does not affect the covariance estimation algorithm

   which can still use the EIGEN_SPARSE_QR algorithm.

   ===============================================================


-- A library with BLAS API found.

-- Found LAPACK library:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Accelerate.framework;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Accelerate.framework

-- Found BLAS library:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Accelerate.framework

-- Building without SuiteSparse.

-- Found CXSparse in: ../cxsparse/Include, building with CXSparse.

-- Google Flags disabled; no tests or tools will be built!

-- Compiling minimal glog substitute into Ceres.

-- Using minimal glog substitute (include): internal/ceres/miniglog

-- Building without OpenMP (disabling multithreading).

-- Looking for C++ include unordered_map

-- Looking for C++ include unordered_map - not found

-- Looking for C++ include tr1/unordered_map

-- Looking for C++ include tr1/unordered_map - not found

-- Unable to find <unordered_map> or <tr1/unordered_map>.

-- Replacing unordered_map/set with map/set (warning: slower!), try
enabling CXX11 option if you expect C++11 to be available.

-- Looking for C++ include memory

-- Looking for C++ include memory - not found

-- Looking for C++ include tr1/memory

-- Looking for C++ include tr1/memory - not found

CMake Error at third_party/ceres-solver/CMakeLists.txt:454 (message):

  Unable to find shared_ptr, try enabling CXX11 option if you expect C++11 to

  be available.


2) After running cmake, I did
cd ../openMVG
make -i

and then

make install -i

It seems that everything gets built and installed except the
following. Any ideas for how can I fix it?

Building CXX object
software/SfM/CMakeFiles/openMVG_main_openMVG2openMVS.dir/main_openMVG2openMVS.cpp.o

In file included from
*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/main_openMVG2openMVS.cpp:18:0*:

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/third_party/cmdLine/cmdLine.h:163:43:*
*warning: *dynamic exception specifications are deprecated in C++11
[*-Wdeprecated*]

     void process(int& argc, char* argv[]) *throw*(std::string) {

                                           *^~~~~*

In file included from
*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/main_openMVG2openMVS.cpp:16:0*:

/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:
In instantiation of '*bool
MVS::ARCHIVE::Save(MVS::ARCHIVE::ArchiveSave&, const _Tp&) [with _Tp =
long unsigned int]*':

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:255:14:*
  required from here

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:121:24:*
*error: *request for member '*serialize*' in '*(long unsigned int&)(&
obj)*', which is of non-class type '*long unsigned int*'

  *const_cast<_Tp&>(obj).serialize*(a, a.version);

  *~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~*

/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:
In instantiation of '*bool
MVS::ARCHIVE::Load(MVS::ARCHIVE::ArchiveLoad&, _Tp&) [with _Tp = long
unsigned int]*':

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:263:14:*
  required from here

*/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/src/software/SfM/InterfaceMVS.h:126:6:*
*error: *request for member '*serialize*' in '*obj*', which is of
non-class type '*long unsigned int*'

  *obj.serialize*(a, a.version);

  *~~~~^~~~~~~~~*

[ 91%] *Linking CXX executable
../../Darwin-x86_64-RELEASE/openMVG_main_openMVG2openMVS*

*g++-7:* *error:
*CMakeFiles/openMVG_main_openMVG2openMVS.dir/main_openMVG2openMVS.cpp.o:
No such file or directory




CMake Error at software/SfM/cmake_install.cmake:221 (file):

  file INSTALL cannot find

  "/Users/chendavies/Documents/LatchAid/LatchAid/openMVG/Darwin-x86_64-RELEASE/openMVG_main_openMVG2openMVS".

Call Stack (most recent call first):

  software/cmake_install.cmake:32 (include)

  cmake_install.cmake:82 (include)


3) I am using Xcode to build my own application where I want to use
OpenMVG as a third party library. How can I set up the build settings
in Xcode which is equivalent of what is described for the CMake file
settings?


Many thanks,


Chen

**Comment by pmoulon** [comment]
Are you using an old version?

Can you please use the develop branch, the issue you encountered should be fixed there?

**Comment by pmoulon** [comment]
You can do: `git clone —recursive https://github.com/openMVG/openMVG.git -b develop`

**Comment by cmdavies** [comment]
Hi Romuald Perrot,

Thanks a lot for your reply.

Unfortunately, I still have the following issue:

when I run: cmake -DCMAKE_BUILD_TYPE=RELEASE -DOpenMVG_BUILD_TESTS=ON
-DOpenMVG_BUILD_EXAMPLES=ON -DOpenMVG_BUILD_SOFTWARES=OFF -fopenmp -G
"Xcode" . ../openMVG/src/

I get the error as below:
… <https://github.com/openMVG/openMVG/issues/1300#>
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown I don't understand why this
happens as both are defined in my .profile file: export
CC=/usr/local/bin/gcc-7 export CXX=/usr/local/bin/c++-7 export
CPP=/usr/local/bin/cpp-7 export LD=/usr/local/bin/gcc-7 export
CPPFLAGS='-I/usr/local/include/c++/7.3.0' export
LDFLAGS='-L/usr/local/lib/'
I am using the latest version from your developer branch.

Could you please help me to identify why this happens? I have been stuck on
configuring and building openMVG for a while but urgently need to use
OpenMVG in my development project.

Many thanks and looking forward to your response!

**Comment by rperrot** [comment]
Ok. 

Could you please tell me some things to test : 
- which version of OSX 
- which version of XCode 
- which version of gcc (fink ? homebrew ?) 
- did you try without CC/CPP/CPPFLAGS and without -fopenmp ? (just to test if standard compilers works fine)

**Comment by rperrot** [comment]
This one works on my mac (latest OSX version : 10.13.4 - latest Xcode version :  9.3 - cmake 3.11.1) on a macbook pro 2015.

```
$ git clone --recursive https://github.com/openMVG/openMVG.git -b develop
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -GXcode . ../openMVG/src/
$ xcodebuild -project openMVG.xcodeproj
```

The last command could be replaced by a build in Xcode.

**Comment by cmdavies** [comment]
Hi Romuald,

Thanks a lot for your prompt reply.

I tried the commands again (in your latest reply above) and get the
following error (please see the attached CMakeError and CMakeOutput files):

-- The C compiler identification is unknown

-- The CXX compiler identification is unknown

CMake Error at CMakeLists.txt:10 (project):

  No CMAKE_C_COMPILER could be found.


CMake Error at CMakeLists.txt:10 (project):

  No CMAKE_CXX_COMPILER could be found.

OSX version : High Sierra 10.13.4
Xcode version : 9.3

cmake version 3.8.2
MacBook Pro (Retina, 13-inch, Early 2015)

The .profile environment variables are:

export CC=/usr/local/bin/gcc-7
export CXX=/usr/local/bin/c++-7
export CPP=/usr/local/bin/cpp-7
export LD=/usr/local/bin/gcc-7
export CPPFLAGS='-I/usr/local/include/c++/7.3.0'
export LDFLAGS='-L/usr/local/lib/'

Many thanks for your help!

**Comment by rperrot** [comment]
Can you try again while removing the CC/CPP/CPPFLAGS of your .profile (make sure you restart your computer to make sure they are not in the cache) ?

**Comment by cmdavies** [comment]
Ok I will try that and get back to you as soon as I can. Thanks a lot!

**Comment by cmdavies** [comment]
Hello,

I have tried to remove the CC/CPP/CPPFLAGS in my .profile and restarted my
Mac before trying to configure the build again. Now it configures perfectly
when running CMake command. Thanks!

However, when I open the the project file in Xcode, change the architecture
to iOS 11.3, and try to build openMVG, I get the following compilation
errors:

clang: error: the clang compiler does not support '-march=broadwell'

when compiling OsiBranchingObject.cpp, OsiAuxInfo.cpp, and
OsiChooseVariable.cpp.

Any suggestions on how to solve these issues?

Many thanks for your timely reply!

**Comment by pmoulon** [comment]
You will need to comment those lines:
```
AutodetectHostArchitecture()
OptimizeForArchitecture()
```
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L111
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L112

**Comment by rperrot** [comment]
@pmoulon This makes me think that we may need in the future to work on the cmake files to help users (and us) to do cross compilation (this issue on iOS is relevant). 

@cmdavies The issue is due to the way cmake works in our case : it tries to set all compiler options in order to provide as much optimisation as possible, but changing the architecture after cmake breaks this choice. As @pmoulon proposed, you need to turn off the optimisation at cmake stage. 

Regarding your initial compilation issues, I think there's one option (maybe CPPFLAGS or LDFLAGS) that fails. It's also generally a bad idea to set CC/CXX/CPPFLAGS at system level since it may break lots of things. If you want to use a different compiler for openMVG, you can use it at cmake stage : 

```
$ CC=clang-mp-6.0 CXX=clang++-mp-6.0 cmake -DCMAKE_BUILD_TYPE=Release . ../openMVG/src/
```

However this may (for now) not be compatible with the -G option since they break the toolchain (this is the issue you got), cmake FAQ indicates to use -D CMAKE_C_COMPILER and -D CMAKE_CXX_COMPILER but it's ignored with -G Xcode (and it goes back to the default compiler).

The issue is that XCode does not recognize custom compiler. There was a trick to do it in XCode 3 but I don't know how to do it in current XCode.

**Comment by cmdavies** [comment]
Hello Pierre and Romuald,

Pierre, I tried to command out the those lines as suggested and then try to use the same cmake command to configure again, but it was unsuccessful as it fails to generate the Xcode project file, cmake_install.cmake, and CMakeScripts.

Please find attached the cmake cache file.

[CMakeCache.txt](https://github.com/openMVG/openMVG/files/1976375/CMakeCache.txt)

Romuald, I think that I still need to set the CC/CXX/CPPFLAGS somewhere. If I only use the command:
cmake -DCMAKE_BUILD_TYPE=Release -GXcode . ../openMVG/src/

I get all my earlier issues of OpenMP flag not detected again such as (Please refer to my comments from the earlier part of this issue thread):

-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
...

**Comment by rperrot** [comment]
Theorically openMP is not mandatory to compile openMVG. That's not exactly an issue. You won't get parallel support.

**Comment by cmdavies** [comment]
Thanks for your response. What about the other issue? Thanks a lot!

I tried to command out the those lines as suggested:

https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L111
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L112

and then try to use the same cmake command to configure again, but it was
unsuccessful as it fails to generate the Xcode project file,
cmake_install.cmake, and CMakeScripts.

**Comment by cmdavies** [comment]
Hello OpenMVG developers!

Thanks a lot for your help earlier, which helped me till I'm stuck with the latest issue (see above). 

Could you please suggest me what to try next? I have done a simple SFM implementation while waiting for your reply. However, it is nowhere near as good as OpenMVG in terms of the performance and accuracy. I would really love to build the OpenMVG for iOS and use it for my iPhone app! And I know the steps to successfully do it will help other developers too. Your help is very much appreciated!

Here are the steps I am using so far:

$ git clone --recursive https://github.com/openMVG/openMVG.git -b develop

Comment out those lines for the iOS platform:
AutodetectHostArchitecture()
OptimizeForArchitecture()
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L111
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L112

$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -GXcode . ../openMVG/src/

Pierre, I tried to command out the those lines as suggested and then try to use the same cmake command to configure again, but it was unsuccessful as it fails to generate the Xcode project file, cmake_install.cmake, and CMakeScripts.

Many thanks in advance!

**Comment by pmoulon** [comment]
Can you please share your cmake log?

**Comment by cmdavies** [comment]
@pmoulon 

These files are here:

[CMakeError.log](https://github.com/openMVG/openMVG/files/2054828/CMakeError.log)
[CMakeOutput.log](https://github.com/openMVG/openMVG/files/2054829/CMakeOutput.log)
[
[CMakeCache.txt](https://github.com/openMVG/openMVG/files/2054835/CMakeCache.txt)
](url)

Thanks a lot!

**Comment by cmdavies** [comment]
@pmoulon 
Any chance to look into the error log? Any suggestions or updates would be greatly appreciated!

**Comment by pmoulon** [comment]
Sorry I did not get the time yet. I will try to give a look this week.

**Comment by cmdavies** [comment]
That’s great thanks Pierre!

**Comment by rperrot** [comment]
There are lot's of errors.

```
gcc-7: error: unrecognized command line option '-fdiagnostics-show-note-include-stack'; did you mean '-fdiagnostics-show-caret'?
gcc-7: error: unrecognized command line option '-fmacro-backtrace-limit=0'; did you mean '-ftemplate-backtrace-limit='?
gcc-7: error: unrecognized command line option '-fpascal-strings'; did you mean '-Wwrite-strings'?
gcc-7: error: unrecognized command line option '-fasm-blocks'; did you mean '-floop-block'?
gcc-7: error: unrecognized command line option '--serialize-diagnostics'; did you mean '--inline-atomics'?
```

Did you successfully compile in command line using gcc7 ?

**Comment by cmdavies** [comment]
@rperrot

I didn’t get to the compiling stage yet. I was just configuring the OpenMVG using cmake. These are my steps below:

$ git clone --recursive https://github.com/openMVG/openMVG.git -b develop

Comment out those lines for the iOS platform:
AutodetectHostArchitecture()
OptimizeForArchitecture()
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L111
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L112

$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -GXcode . ../openMVG/src/

However, when I tried to command out the those lines as @pmoulon suggested and then try to use the same cmake command to configure again, but it was unsuccessful as it fails to generate the Xcode project file, cmake_install.cmake, and CMakeScripts.

**Comment by rperrot** [comment]
I can configure commenting the following line : 

https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L435

```
string(REPLACE " " ";" REPLACED_CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
```

**Comment by cmdavies** [comment]
@rperrot 
You are right, I can now configure OpenMVG by following your suggestion above and get a Xcode project file. I will try to open the project file and change the architecture settings etc to see if I can build OpenMVG using Xcode. I will give you an update later today. Thanks a lot!

**Comment by rperrot** [comment]
@pmoulon The fix is not a good idea, it may break something elsewhere. The error on my mac is : 

```
CMake Error at CMakeLists.txt:424 (string):
  string sub-command REPLACE requires at least four arguments.
```

But there are 4 arguments ... Does bug only on cmake mac ? 
(note: we may open a new thread for this new issue).

**Comment by cmdavies** [comment]
@rperrot 
I tried your suggestion to comment out the following line :

https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L435

string(REPLACE " " ";" REPLACED_CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})

Although when running Cmake command it configures and creates the Xcode project, when I open the project file in Xcode, change the architectures to armv7 armv7s and arm64, and build the project in Xcode, I get the following error again:

clang: error: the clang compiler does not support '-march=broadwell'

I was previously advised by @pmoulon to comment out:

AutodetectHostArchitecture()
OptimizeForArchitecture()
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L111
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L112

to solve this issue. However, this will go back to the first issue of not being able to configure using Cmake again. 

Any suggestions or directions on how to solve these issues?

I'm sure many people will run into the same issues when trying to build OpenMVG for iOS to develop the SFM app for iPhone. Any help or directions will be greatly appreciated!

**Comment by pmoulon** [comment]
Can we close this?

**Comment by cmdavies** [comment]
Yes we can close this one and for future reference, some issues listed here have been solved in #1300. Thanks a lot for your help and suggestions!

**Comment by hblanken** [comment]
From this thread I understand that openMP is not needed necessarily for compiling on Mac.
I had similar issues for Mojave MacOS install.

So I did this-just for the record:

My solution: 
In CMakeList.txt I comment out the section starting on line 130

# OpenMP detection
